#
# Message in A bottle Docker Compose file
#

version: "3.6"

services:
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "5342:5342"
    env_file:
      - env_file

  mib_lottery:
    <<: &mib_lottery
      # Building the image
      image: "mib-lottery:latest"
      build:
        context: .
        dockerfile: Dockerfile
    ports:
     - "5004:5004"
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
      - FLASK_ENV=production
    depends_on:
      - db
      - migrations
      - redis

  migrations:
    #
    # this service is used to apply migrations on db
    #
    <<: *mib_lottery
    command: flask db upgrade
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    restart: on-failure

  redis_lottery:
    container_name: redis_lottery
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
        
  celery_worker_lottery:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -b "redis://redis:6379" -A wsgi.celery_app worker --loglevel=info
    links:
      - redis_lottery
    depends_on:
      - redis_lottery

  celery_beat_lottery:
    build:
      context: .
    command: celery -b "redis://redis:6379" -A wsgi.celery_app beat --loglevel=info
    depends_on:
      - redis_lottery

# Declaring all volumes
volumes:
  pgdata: # for maintaing db data
