openapi: 3.0.1

info:
  title: Lottery Service API
  description: Lottery Microservice of Message in a Bottle Application
  version: 0.2-oas3

servers:
  - url: /

paths:
  /is_participant:
    post:
      tags: [ Lottery ]
      summary: return 201 if the user is a partecipate to the lottery, 202 else
      operationId: mib.resource.lottery.is_participant
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
      description: return 201 if the user is a partecipate to the lottery, 202 else
      responses:
        '201':
          description: user is participant
        '202':
          description: user is not a participant
  /join_lottery:
    post:
      tags: [ Lottery ]
      summary: return 201 if the user is a new participant, 302 generic error
      operationId: mib.resource.lottery.join_lottery
      description: return 201 if the user is a new participant, 302 generic error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
      responses:
        '201':
          description: user is participant
        '302':
          description: user is not a participant
